# Generated by Django 5.1.2 on 2025-09-29 21:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Court Name", max_length=200)),
                (
                    "court_type",
                    models.CharField(
                        choices=[
                            ("SC", "Supreme Court of India"),
                            ("HC", "High Court"),
                            ("DC", "District Court"),
                            ("SC_MAG", "Sessions Court"),
                            ("MAG", "Magistrate Court"),
                            ("CJM", "Chief Judicial Magistrate Court"),
                            ("JMFC", "Judicial Magistrate First Class"),
                            ("FAMILY", "Family Court"),
                            ("CONSUMER", "Consumer Court"),
                            ("LABOUR", "Labour Court"),
                            ("TRIBUNAL", "Tribunal"),
                            ("DEBTS", "Debts Recovery Tribunal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(help_text="City/District", max_length=200),
                ),
                ("state", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                (
                    "contact_info",
                    models.TextField(blank=True, help_text="Phone, Email, etc."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["court_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("occupation", models.CharField(blank=True, max_length=100)),
                (
                    "aadhar_number",
                    models.CharField(
                        blank=True, help_text="Aadhar Card Number", max_length=12
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True, help_text="PAN Card Number", max_length=10
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional client information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("lawyer", "name")},
            },
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_number",
                    models.CharField(help_text="Court Case Number", max_length=50),
                ),
                (
                    "case_title",
                    models.CharField(
                        help_text="Short case description", max_length=300
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Civil Case"),
                            ("CRIMINAL", "Criminal Case"),
                            ("FAMILY", "Family Dispute"),
                            ("PROPERTY", "Property Dispute"),
                            ("LABOUR", "Labour Dispute"),
                            ("CONSUMER", "Consumer Complaint"),
                            ("MATRIMONIAL", "Matrimonial Case"),
                            ("CHEQUE_BOUNCE", "Cheque Bounce Case"),
                            ("ARBITRATION", "Arbitration"),
                            ("WRIT", "Writ Petition"),
                            ("APPEAL", "Appeal"),
                            ("REVISION", "Revision Petition"),
                            ("BAIL", "Bail Application"),
                            ("COMPANY", "Company Law"),
                            ("TAX", "Tax Matter"),
                            ("BANK_RECOVERY", "Bank Recovery"),
                            ("INSURANCE", "Insurance Claim"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filing_date", models.DateField(help_text="Date case was filed")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("ADJOURNED", "Adjourned"),
                            ("JUDGMENT_RESERVED", "Judgment Reserved"),
                            ("WON", "Won"),
                            ("LOST", "Lost"),
                            ("SETTLED", "Settled"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("DISMISSED", "Dismissed"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed case description"),
                ),
                (
                    "legal_issues",
                    models.TextField(blank=True, help_text="Key legal issues"),
                ),
                (
                    "case_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "fees_charged",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fees_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("next_hearing_date", models.DateTimeField(blank=True, null=True)),
                (
                    "limitation_date",
                    models.DateField(
                        blank=True, help_text="Limitation period expiry", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="core.client",
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="core.court",
                    ),
                ),
            ],
            options={
                "ordering": ["-next_hearing_date", "-created_at"],
                "unique_together": {("lawyer", "case_number", "court")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PLAINT", "Plaint/Petition"),
                            ("WRITTEN_STATEMENT", "Written Statement"),
                            ("AFFIDAVIT", "Affidavit"),
                            ("EVIDENCE", "Evidence Document"),
                            ("JUDGMENT", "Judgment/Order"),
                            ("NOTICE", "Notice"),
                            ("SUMMONS", "Summons"),
                            ("APPLICATION", "Application"),
                            ("REPLY", "Reply"),
                            ("REJOINDER", "Rejoinder"),
                            ("VAKALATNAMA", "Vakalatnama"),
                            ("POWER_OF_ATTORNEY", "Power of Attorney"),
                            ("CONTRACT", "Contract/Agreement"),
                            ("CORRESPONDENCE", "Correspondence"),
                            ("RECEIPT", "Receipt/Bill"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="File system path or cloud URL",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("document_date", models.DateField(help_text="Date of the document")),
                ("received_date", models.DateField(default=datetime.date.today)),
                ("is_original", models.BooleanField(default=False)),
                ("is_certified_copy", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-document_date"],
            },
        ),
        migrations.CreateModel(
            name="Hearing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hearing_date", models.DateTimeField()),
                (
                    "hearing_type",
                    models.CharField(
                        choices=[
                            ("FIRST_HEARING", "First Hearing"),
                            ("ARGUMENTS", "Arguments"),
                            ("EVIDENCE", "Evidence Recording"),
                            ("CROSS_EXAMINATION", "Cross Examination"),
                            ("FINAL_ARGUMENTS", "Final Arguments"),
                            ("JUDGMENT", "Judgment"),
                            ("MENTION", "Mention"),
                            ("INTERIM_APPLICATION", "Interim Application"),
                            ("BAIL_HEARING", "Bail Hearing"),
                            ("STATUS_CONFERENCE", "Status Conference"),
                        ],
                        max_length=20,
                    ),
                ),
                ("court_room", models.CharField(blank=True, max_length=50)),
                ("judge_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("ADJOURNED", "Adjourned"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                ("purpose", models.TextField(help_text="Purpose of this hearing")),
                (
                    "outcome",
                    models.TextField(
                        blank=True, help_text="What happened in the hearing"
                    ),
                ),
                (
                    "next_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Next hearing date if adjourned",
                        null=True,
                    ),
                ),
                ("preparation_notes", models.TextField(blank=True)),
                ("documents_required", models.TextField(blank=True)),
                ("witnesses_required", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hearings",
                        to="core.case",
                    ),
                ),
            ],
            options={
                "ordering": ["-hearing_date"],
            },
        ),
        migrations.CreateModel(
            name="TaskReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("HEARING_PREP", "Hearing Preparation"),
                            ("DOCUMENT_FILING", "Document Filing"),
                            ("LIMITATION", "Limitation Deadline"),
                            ("CLIENT_MEETING", "Client Meeting"),
                            ("COURT_FEE", "Court Fee Payment"),
                            ("APPEAL_DEADLINE", "Appeal Deadline"),
                            ("COMPLIANCE", "Compliance Matter"),
                            ("FOLLOW_UP", "Follow Up"),
                            ("OTHER", "Other Task"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                ("reminder_date", models.DateTimeField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("is_overdue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="core.case",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-priority"],
            },
        ),
    ]
